[build-system]
requires = ["uv_build>=0.7.19"]
build-backend = "uv_build"


[project]
name = "flake8-lazy"
version = "0.1.0"
authors = [
  { name = "Henry Schreiner", email = "henryschreineriii@gmail.com" },
]
description = "Detect imports that can be lazy"
readme = "README.md"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 1 - Planning",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering",
  "Typing :: Typed",
]
dependencies = []

[project.scripts]
flake8-lazy = "flake8_lazy:main"

[project.entry-points."flake8.extension"]
LZY = "flake8_lazy:LazyImportChecker"

[project.urls]
Homepage = "https://github.com/henryiii/flake8-lazy"
"Bug Tracker" = "https://github.com/henryiii/flake8-lazy/issues"
Discussions = "https://github.com/henryiii/flake8-lazy/discussions"
Changelog = "https://github.com/henryiii/flake8-lazy/releases"


[dependency-groups]
test = [
  "pytest >=9",
  "pytest-cov >=7",
]
dev = [
  { include-group = "test" },
]
docs = [
    "zensical>=0.0.20",
]


[tool.pytest]
minversion = "9.0"
addopts = ["-ra", "--showlocals"]
strict = true
filterwarnings = [
  "error",
]
log_level = "INFO"
testpaths = [
  "tests",
]


[tool.coverage]
run.source = ["flake8_lazy"]
report.exclude_also = [
  '\.\.\.',
  'if typing.TYPE_CHECKING:',
]

[tool.mypy]
files = ["src", "tests"]
python_version = "3.10"
warn_unused_configs = true
strict = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]
warn_unreachable = true
disallow_untyped_defs = false
disallow_incomplete_defs = false

[[tool.mypy.overrides]]
module = "flake8_lazy.*"
disallow_untyped_defs = true
disallow_incomplete_defs = true


[tool.ruff]
show-fixes = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "D",       # Too many doc requests
  "PLR09",   # Too many <...>
  "PLR2004", # Magic value used in comparison
  "S101",    # Assert is used by mypy and pytest
]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["T20", "INP001"]
"noxfile.py" = ["T20"]


[tool.pylint]
py-version = "3.10"
ignore-paths = [".*/_version.py"]
reports.output-format = "colorized"
similarities.ignore-imports = "yes"
messages_control.disable = [
  "design",
  "fixme",
  "line-too-long",
  "missing-module-docstring",
  "missing-function-docstring",
  "wrong-import-position",
]
